version: '2'
services:
  requestor:
    command: npm start
    build:
      context: ./request-service
      dockerfile: Dockerfile.request
    image: ${REQUEST_IMAGE}:${VERSION}
    container_name: ${REQUEST_CONTAINER}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - ZMQ_RES_ADDRESS=tcp://responder:${ZMQ_PORT}
      - HTTP_PORT=${HTTP_PORT}
    networks:
      - zeromq-http-req-res

  responder:
    command: npm start
    build:
      context: ./response-service
      dockerfile: Dockerfile.response
    image: ${RESPONSE_IMAGE}:${VERSION}
    #image: ${RESPONSE_IMAGE}:${GITHASH}
    container_name: ${RESPONSE_CONTAINER}
    ports:
      - "${ZMQ_PORT}:${ZMQ_PORT}"
    environment:
      - ZMQ_REQ_ADDRESS=tcp://*:${ZMQ_PORT}
      - ZMQ_PORT=${ZMQ_PORT}
    networks:
      - zeromq-http-req-res

networks:
  zeromq-http-req-res:
    driver: bridge
