FROM xybersolve/zeromq-base:latest

MAINTAINER Greg Milligan <xybersolve@gmail.com>

# ARG ZMQ_PORT
# ARG HTTP_PORT
# ARG HTTP_HOST

ENV ZMQ_PORT ${ZMQ_PORT}

COPY ./ /app
WORKDIR /app

RUN rm -rf node_modules && \
    apt-get update && \
    npm install

EXPOSE $ZMQ_PORT

CMD ["npm", "start"]
